FROM python:3.6
LABEL maintainer="Vishnu"
RUN apt update && apt install -y ca-certificates && apt install -y libpq-dev postgresql-client
WORKDIR /app
ADD . /app
COPY ./matchupdater/ /app
RUN cd /app && pip install -r requirements.txt && rm -rf /root/.cache
#RUN chmod +x launch.sh
ENV DATABASE_URL=postgres://ycaffmkrsgyjsm:95e7001c889477e404a8b767df66b68907039b6cb451881501105e3880b64603@ec2-54-90-211-192.compute-1.amazonaws.com:5432/df0lpdam7ipsq1
CMD ["python", "-u" ,"main.py"]
